### PR TITLE
Added Table.py for class structure and fixed file reference in main.py

### PR DESCRIPTION
**Pull request by PaulGurman**

### CODE REVIEW

**Comment by mikedelgaudio** [comment]
@PaulGurman you probably need to comment `run()` for the pytest to do its thing for now

**Comment by PaulGurman** [comment]
@mikedelgaudio ah my bad, I’ll fix that

**Comment by mikedelgaudio** [comment]
@PaulGurman ill take a look, lets get shannons in

**Comment by mikedelgaudio** [comment]
@PaulGurman I attempted to merge to master - and I began implementing more your class, but I think we need a `toString()` something like that?

Screen Shot 2020-05-31 at 2 09 25 PM

**Comment by mikedelgaudio** [comment]
@PaulGurman yeah the git action isn't getting the table - something I am not seeing with the relative file path system of python `__init__.py` and such still don't make too much sense to me. @shannonhobby maybe one of you know how can we import these items properly to the test file with a relative file scheme. 

Here is an example of the consistent errors:
Screen Shot 2020-06-01 at 6 05 51 PM

**Pull request merged**
